plugins {
    id 'com.android.application'
}
android {
    namespace 'com.allenscreations.autorelease'
    compileSdk 34
    defaultConfig {
        applicationId "com.allenscreations.autorelease"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
